name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore src/Aloe.Utils.Template/Aloe.Utils.Template.csproj
        
      - name: Build
        run: dotnet build src/Aloe.Utils.Template/Aloe.Utils.Template.csproj --configuration Release
      
      - name: Pack (symbols+source)
        run: dotnet pack src/Aloe.Utils.Template/Aloe.Utils.Template.csproj --configuration Release --no-build --include-symbols --include-source --output ./nupkgs
      
      - name: Publish to NuGet
        run: dotnet nuget push ./nupkgs/*.nupkg ./nupkgs/*.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
